version: '3.8'

services:
  # Database Service
  db:
    image: mysql:8.0
    container_name: metrics_db
    restart: always
    command: --innodb-buffer-pool-size=64M
    environment:
      # Pulling secrets from .env file
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${DB_NAME}
    # Port 3306 is NOT mapped to the host. 
    # Only 'api' service can reach it via internal docker network 'db:3306'.
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Backend API Service
  api:
    build: .
    container_name: metrics_api
    restart: always
    ports:
      - "${API_PORT}:8000" # Exposing only the API to the world
    environment:
      DB_HOST: db
      # Using variables from .env to match the DB config
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

volumes:
  db_data: